version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/agentapi"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/windows-agent"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/wsl-service"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/tools"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "pub"
    # So we update grpc and protobuf packages
    directory: "/agentapi/dart"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/gui/packages/p4w_ms_store"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/gui/packages/ubuntupro"
    schedule:
      interval: "daily"