version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/agent-api"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/windows-agent"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/wsl-service"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/tools"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
