version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/agentapi"
    commit-message:
      prefix: "deps(agentapi): "
    schedule:
      interval: "weekly"
      day: "thursday"

  - package-ecosystem: "gomod"
    directory: "/windows-agent"
    commit-message:
      prefix: "deps(windows-agent): "
    schedule:
      interval: "weekly"
      day: "thursday"

  - package-ecosystem: "gomod"
    directory: "/common"
    commit-message:
      prefix: "deps(common): "
    schedule:
      interval: "weekly"
      day: "thursday"

  - package-ecosystem: "gomod"
    directory: "/end-to-end"
    commit-message:
      prefix: "deps(end-to-end): "
    schedule:
      interval: "weekly"
      day: "thursday"

  - package-ecosystem: "gomod"
    directory: "/tools"
    commit-message:
      prefix: "deps(tools): "
    schedule:
      interval: "weekly"
      day: "thursday"

  - package-ecosystem: "gomod"
    directory: "/wsl-pro-service"
    commit-message:
      prefix: "deps(wsl-pro-service): "
    schedule:
      interval: "weekly"
      day: "thursday"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    commit-message:
      prefix: "deps(gh-actions): "
    schedule:
      interval: "weekly"
      day: "thursday"

  - package-ecosystem: "pub"
    # So we update grpc and protobuf packages
    directory: "/agentapi/dart"
    commit-message:
      prefix: "deps(agentapi): "
    schedule:
      interval: "weekly"
      day: "thursday"
  - package-ecosystem: "pub"
    directory: "/gui/packages/p4w_ms_store"
    commit-message:
      prefix: "deps(gui-p4w_ms_store): "
    schedule:
      interval: "weekly"
      day: "thursday"
  - package-ecosystem: "pub"
    directory: "/gui/packages/ubuntupro"
    commit-message:
      prefix: "deps(gui-ubuntupro): "
    schedule:
      interval: "weekly"
      day: "thursday"
