name: Check diff
description: Checks that there is diff within the repository on discrete files.

inputs:
  files-to-validate:
    required: true
    description: "File pattern to check the diff for. (Use git's syntax)"

runs:
  using: "composite"
  steps:
    - name: Check diff
      shell: bash
      run : |
        #  Check diff
         MODIFIED=`git status --porcelain ${{ inputs.files-to-validate }}`

        if [ -z "${MODIFIED}" ]; then
          echo "Success"
          exit 0
        fi

        # Ignore modification time and protoc version.
        FILTERED=`git difftool -y -x "diff -I 'modTime' -I '^//.*protoc.*v'" -- ${{ inputs.files-to-validate }}`

        if [ -z "${FILTERED}" ]; then
          echo "Success"
          exit 0
        fi

        echo "Error: the following files don't match their committed version:"
        echo "${MODIFIED}"
        
        DIFF=`git diff --ignore-cr-at-eol -- ${{ inputs.files-to-validate }}`
        if [ -z "${DIFF}" ]; then
          # If all files are only added or removed, they won't show up in the diff
          exit 1
        fi

        echo ""
        echo "::group::See diff"
        echo "${DIFF}"
        echo "::endgroup::"
        exit 1
