name: Report an issue
description: Create a bug report to fix an issue
title: "Issue: "
labels: "bug"
body:
  - type: markdown
    attributes:
      value: >
        :warning: **Please do not report security vulnerabilities here**

        Be careful with sensitive information and security vulnerabilities.

        Thanks for taking the time to report an issue and helping to improve Ubuntu Pro for WSL! Please fill out the form below as
        best as you can so that we can help you.

        Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general
        support or usage questions, use [Ubuntu Discourse](https://discourse.ubuntu.com/c/desktop/8).

        By submitting an Issue to this repository, you agree to the terms within the
        [Ubuntu Code of Conduct](https://ubuntu.com/community/code-of-conduct).
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      options:
        - label: I have searched the existing issues and found none that matched mine
          required: true
  - type: textarea
    attributes:
      label: Describe the issue
      description: >
        Provide a clear and concise description of what the issue is, including what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce it
      description: >
        Detail the steps taken to reproduce this error, what was expected, and whether this issue can be reproduced
        consistently or if it is intermittent.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...

        Please include screenshots (you can drag any image here) where applicable. Redact any sensitive information.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Installed versions
      value: |
        * Windows version: *Run cmd /c ver*
        * WSL version: *wsl --status*
        * Windows application version: Open Pro for Windows GUI, check version in status bar.
        * WSL distribution: Name of the Ubuntu distribution you are using
        * WSL OS: (`/etc/os-release`) in the wsl instance
        * ubuntu wsl service version: (`apt policy wsl-pro-service` output)
  - type: textarea
    attributes:
      label: System logs
      description: >
        Drag and drop the following files here:

        ```
        %USERPROFILE%/.ubuntupro/log
        ```,
        ```
        %USERPROFILE%/.ubuntupro/log.old
        ```

        Also, report any impacted WSL instance logs, by pasting here the output of:

        ```
        journalctl -u wsl-pro.service
        ```
  - type: checkboxes
    attributes:
      label: Double check your logs
      options:
        - label: I have redacted any sensitive information from the logs
          required: true
  - type: textarea
    attributes:
      label: Additional information
      description: >
        Should there be any other contextual information that might be useful, please provide it here.
        Please take a look at our [Troubleshooting guide](../#troubleshooting) to understand a bit more about what you
        can do to get more information and logs about the project.
      placeholder: Remember to redact any sensitive information from them.
