name: Request a feature
description: Suggest new functionality or improvements for this project
title: "Feature: "
labels: "feature"
body:
  - type: markdown
    attributes:
      value: >
        :warning: **Please do not report security vulnerabilities here**

        Be careful with sensitive information and security vulnerabilities. In order to report bugs that could contain
        sensitive information:
        - If the bug is on the Windows side (Graphical interface or agent running as a background service on Windows):
        Please use the advisories page of the repository and not a public bug report.

        - If the bug affects the `ubuntu-wsl` service running on Ubuntu: please use [Launchpad](https://bugs.launchpad.net/ubuntu/+source/ubuntu-wsl-service/+filebug) instead.
        On Ubuntu machines, you can use `ubuntu-bug ubuntu-wsl-service` to collect relevant information.


        Thanks for taking the time to report an issue and helping to improve Ubuntu Pro for WSL! Please fill out the form below as
        best as you can so that we can help you.

        Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general
        support or usage questions, use [Ubuntu Discourse](https://discourse.ubuntu.com/c/desktop/8).

        By submitting an Issue to this repository, you agree to the terms within the
        [Ubuntu Code of Conduct](https://ubuntu.com/community/code-of-conduct).
  - type: checkboxes
    attributes:
      label: Is there an existing request for this feature?
      options:
        - label: I have searched the existing issues and found none that matched mine
          required: true
  - type: textarea
    attributes:
      label: Describe the feature
      description: >
        A clear and concise description of what the problem is. Ex.: \"I'm always frustrated when ...\"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the ideal solution
      description: >
        A clear and concise description of what you want to happen.
  - type: textarea
    attributes:
      label: Alternatives and current workarounds
      description: >
        A clear and concise description of any alternatives you've considered or any workarounds that are currently in
        place.
  - type: textarea
    attributes:
      label: "Ubuntu System information"
      description: >
        If the bug is on the `ubuntu-wsl` service running in the WSL machine, you can run `ubuntu-bug ubuntu-wsl-service --save=/tmp/report.txt`
        and drag the file below.

        It will contain useful information pertaining to the system and the packages installed.
  - type: textarea
    attributes:
      label: "Installed versions"
      value: |
        TODO: we should probably have a binary on the windows side collecting all this for you.

        * Windows version: TODO, describe how to get it
        * WSL version: TODO, describe how to get it
        * WSL distribution: TODO, describe how to get it
        * Windows application version:  TODO, describe how to get it
        * WSL OS: (`/etc/os-release`) in the wsl instance
        * ubuntu wsl service version: (`apt policy ubuntu-wsl-service` output)
  - type: textarea
    attributes:
      label: Additional information
      description: >
        Should there be any other contextual information that might be useful, please provide it here.
        Please take a look at our [Troubleshooting guide](../#troubleshooting) to understand a bit more about what you
        can do to get more information and logs about the project.
      placeholder: Remember to redact any sensitive information from them.
  - type: checkboxes
    attributes:
      label: Double check your logs
      options:
        - label: I have redacted any sensitive information from the logs
          required: true
