name: Load the contents of a file
description: Loads the contents of a file.

inputs:
  path:
    required: false
    description: "Path to the file to be read"

outputs:
  contents:
    description: "The contents of the loaded file."
    value: ${{ steps.load.outputs.data }}

runs:
  using: "composite"
  steps:
    - name: Load
      id: load
      shell: bash
      run : |
        # Load from ${{ inputs.path }}
        set -eu
        data=$(cat '${{ inputs.path }}')

        # Remove endlines
        data="${data//[$'\r\n']}"

        # Store result
        echo "data=$data" >> $GITHUB_OUTPUT
    - name: Show contents
      shell: bash
      run: |
        cat << EOF
        ${{ steps.load.outputs.data }}
        EOF