name: Load JSON
description: Loads JSON data from a file.

inputs:
  path:
    required: true
    description: "Path to the JSON file"

outputs:
  data:
    description: "Loaded data. Can be accessed like a Github matrix."
    value: ${{ fromJson(steps.load.outputs.data) }}

runs:
  using: "composite"
  steps:
    - name: Load JSON
      id: load
      shell: bash
      run : |
        # Load JSON from ${{ inputs.path }}
        set -eu
        data=$(cat '${{ inputs.path }}')

        # Remove endlines
        data="${data//[$'\r\n']}"

        # Store result (must be in a single line)
        echo "data='$data'" >> $GITHUB_OUTPUT