name: Build debian package
description: Builds a debian package and uploads the artifact

inputs:
  source-dir:
    required: false
    description: "Directory where the source is located"
  docker-image:
    required: false
    default: ubuntu:rolling
    description: "The docker image used to build the package"

runs:
  using: "composite"
  steps:
    - name: Set up source package build
      shell: bash
      working-directory: ${{ inputs.source-dir }}
      run: |
        set -eu

        echo "::group::Append commit SHA to local version"
        DEBIAN_FRONTEND=noninteractive sudo apt install -y devscripts
        debchange --local "_${{ inputs.docker-image }}+${{ github.sha }}" "Github build. Job id: ${{ github.run_id }}. Attempt: ${{ github.run_number }}."
        echo "::endgroup::"

        echo "::group::Parsing name and version"
        echo PKG_NAME="$( dpkg-parsechangelog --show-field source )" >> $GITHUB_ENV
        echo PKG_VERSION="$( dpkg-parsechangelog --show-field version )" >> $GITHUB_ENV
        echo "::endgroup::"

        echo "::group::Prepare source build"
        echo SOURCE_DIR="$(pwd)/$( mktemp --directory --tmpdir=. )" >> $GITHUB_ENV
        echo "::endgroup::"
    - name: Build source package
      uses: jtdor/build-deb-action@v1
      with:
        artifacts-dir: ${{ env.SOURCE_DIR }}
        source-dir: ${{ inputs.source-dir }}
        docker-image: ${{ inputs.docker-image }}
        buildpackage-opts: --build=source
        extra-build-deps: ca-certificates git
        before-build-hook: |
          GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          git config --system url."https://api:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
    - name: Set up pacakge build
      shell: bash
      working-directory: ${{ env.SOURCE_DIR }}
      run: |
        set -eu

        echo "::group::Extract source package"
        SOURCE_DIR="$(pwd)/$( mktemp --directory --tmpdir='.' )"
        dpkg-source --extract *.dsc "${SOURCE_DIR}"
        echo SOURCE_DIR="${SOURCE_DIR}" >> $GITHUB_ENV
        echo "::endgroup::"
        
        echo "::group::Create output directory"
        echo OUTPUT_DIR="$(pwd)/$( mktemp --directory --tmpdir='.' )" >> $GITHUB_ENV
        echo "::endgroup::"
    - name: Build package
      uses: jtdor/build-deb-action@v1
      with:
        artifacts-dir: ${{ env.OUTPUT_DIR }}
        source-dir: ${{ env.SOURCE_DIR }}
        docker-image: ${{ inputs.docker-image }}
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.PKG_NAME }}_${{ env.PKG_VERSION }}
        path: ${{ env.OUTPUT_DIR }}/
        if-no-files-found: error
